Repository rt-net/raspimouse2, pull requests merged in 2020-06, with the labels that each got.

#21 Update CMakeLists.txt for exporting include dir
  raspimouse/CMakeLists.txt
Labels: Type: Feature

#22 V1.0.0
  raspimouse/CHANGELOG.rst
  raspimouse/package.xml
  raspimouse_msgs/CHANGELOG.rst
  raspimouse_msgs/package.xml
Labels: Type: Maintenance

#23 Fix documents of release 1.0.0
  raspimouse/CHANGELOG.rst
  raspimouse/package.xml
  raspimouse_msgs/CHANGELOG.rst
  raspimouse_msgs/package.xml
Labels: Type: Documentation

#25 Add release tag actions
  .github/workflows/add-tag.yml
Labels: Type: Maintenance

#24 Release 1.0.1
  raspimouse/CHANGELOG.rst
  raspimouse/package.xml
  raspimouse_msgs/CHANGELOG.rst
  raspimouse_msgs/package.xml
Labels: Type: Maintenance

#26 Update README.md
  README.md
Labels: Type: Documentation
