Repository rt-net/raspimouse2, pull requests merged in 2020-05, with the labels that each got.

#16 Change pulse counter for calculating odometry accurately
  raspimouse/src/raspimouse_component.cpp
Labels: Type: Feature

#18 Release 0.2.0
  raspimouse/CHANGELOG.rst
  raspimouse/package.xml
  raspimouse_msgs/CHANGELOG.rst
  raspimouse_msgs/package.xml
Labels: Type: Maintenance

#17 Add on_shutdown callback
  raspimouse/include/raspimouse/raspimouse_component.hpp
  raspimouse/src/raspimouse_component.cpp
Labels: Type: Feature

#19 Update README.md
  README.md
Labels: Type: Documentation

#20 Fix package.xml
  raspimouse/package.xml
Labels: Type: Bug
